title: ∀Lab
subtitle: Mέτατεχ
minimal_mistakes_skin: default
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages
  - _projects

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


collections:
  projects:
    output: true
    permalink: /:collection/:path


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: false

feed:
  categories:
    - wotd
